// let arrayStr = ['Meri', 'Andriy', 'Daniy','Orest','Azazel'];
// let arrayNumb = [15, 10, 1, 25, 5];
// let arrayMix = [40, 'lilit', false, true, - 26, 95, 'Adam', false, 14, 'me', 'photo', 45, true, 'homework', true];
// let arrayVacuum = [];
// console.log (arrayStr);
// console.log(arrayNumb);
// console.log(arrayMix);
// arrayVacuum[1] = 'hello';
// arrayVacuum[5] = 'world';
// arrayVacuum[3] = 40;
// arrayVacuum[24] = true;
// console.log(arrayVacuum);
